// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://howfeebkhupqckdrjfph.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhvd2ZlZWJraHVwcWNrZHJqZnBoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzNTE3NTIsImV4cCI6MjA2NTkyNzc1Mn0.l0Bj0KvHdThNvSaSXgKVDcChkP_d58xzr6ui0pK82S0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);